### ISSUE TITLE
POST contains no data?

### ISSUE THREAD

**Issue by mpisat** [meetecho/simple-whep-client#3]
I'm testing it but it is sending an empty POST request to my /api/whep endpoint.

It was very difficult to get all required gstreamer packages and I can't get it to work...

**Comment by lminiero** [comment]
As explained in the README:

> Notice, though, that just as the WHEP server, this client only implements sessions based on the server offering, meaning it will not work in case the WHEP server expects an offer from the client instead.

As such, we send an empty post and expect an offer from the server instead.

**Comment by lminiero** [comment]
If you're using this with our WHEP server (and Janus), it will work.

**Comment by mpisat** [comment]
Well, I was hoping WHIP and WHEP will standardize WebRTC but so far I only had good luck with WHIP and WHIP alone.

**Comment by lminiero** [comment]
The standardization for WHIP is almost done, WHEP has just started. You'll have to endure many changes before that's complete too.
